#:kivy 2.0.1

<MyLayout>
    BoxLayout:
        orientation: 'vertical'
        size: root.width, root.height

        padding: 50
        spacing: 20 

        Label:
            id: label_id
            text: 'Select an item in the spinner below'

        Spinner:
            id: spinner_id
            text: 'Some items to choose'
            values: ['pizza', 'milkshake', 'cats', 'cocas' ]
            on_text: root.spinner_clicked( spinner_id.text )

        Label:
            text: ''