#:kivy 2.0.1

<MyLayout>
    BoxLayout:
        orientation: 'vertical'
        size: root.width, root.height

        padding: 50
        spacing: 20 

        Label: 
            id: my_label 
            text: 'Hello, do something nice'
            font_size: 32 

        Button: 
            text: 'So, press me!'
            font_size: 32 
            size_hint: .5, .5 
            pos_hint: {'center_x': 0.5 }
            on_release: root.animate_it( self )