#:kivy 2.0.1

<MyLayout>
    id: my_widget 

    BoxLayout:
        orientation: 'vertical'
        size: root.width, root.height

        padding: 50
        spacing: 20 

        Image:
            id: my_image
            source: ''

        # FileChooserListVie:
        FileChooserIconView: 
            id: filechooser
            on_selection: my_widget.selected( filechooser.selection )
            
